name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: build
          path: dist
      
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Restore Cache
        id: cache-restore
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies if No Cache Hit
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: npm ci
        
      - name: Build
        run: npm run build:vercel
        
      - name: Push to build branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo -e "\n# Remove old files"
          rm -rfv dist/api/*
          rm -rfv dist/public/*
          echo -e "\n# Move build files to dist"
          rsync -vaI api/ dist/api
          rsync -vaI public/ dist/public
          echo -e "\n# Commit/Push"
          cd dist
          git add --all .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "build: vercel build for ${GITHUB_SHA}" || true
          git push origin build
